version: '3.5'
services:
  monitoring-api:
    image: monitoring-api:latest
    container_name: monitoring-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/code/
    command: sh /code/run.sh