version: '3.5'
services:
  monitoring-api:
    image: monitoring-api:latest
    container_name: monitoring-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/code/
    networks:
      - my_network
    command: sh /code/run.sh

networks:
  my_network:
    driver: bridge
    external: true